# Generated by Django 6.1.1 on 2026-09-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(max_length=50, unique=True, verbose_name='Mã hàng')),
                ('ten_hang', models.CharField(max_length=150, verbose_name='Tên hàng hóa')),
                ('so_luong_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số lượng tồn')),
                ('gia_nhap', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá nhập')),
                ('gia_xuat', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá xuất')),
                ('ton_toi_thieu', models.DecimalField(decimal_places=2, default=10, max_digits=18, verbose_name='Tồn tối thiểu')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True, verbose_name='Tên đăng nhập')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Mật khẩu mã hóa')),
                ('role', models.CharField(default='USER', max_length=20, verbose_name='Quyền hạn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
    ]
