# Generated by Django 6.1.1 on 2026-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanghoa',
            options={'verbose_name': 'Hàng Hóa'},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'Người Dùng'},
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='mo_ta',
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='ton_toi_thieu',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='ho_ten',
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='so_luong_ton',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='ten_hang',
            field=models.CharField(max_length=255, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='role',
            field=models.CharField(default='staff', max_length=50, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ten_dang_nhap',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên đăng nhập'),
        ),
        migrations.AlterModelTable(
            name='hanghoa',
            table='HangHoa',
        ),
        migrations.AlterModelTable(
            name='nguoidung',
            table='NguoiDung',
        ),
    ]
