# Generated by Django 6.1.1 on 2026-09-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_hanghoa_options_alter_nguoidung_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanghoa',
            options={'verbose_name': 'Hàng Hóa', 'verbose_name_plural': 'Danh mục hàng hóa'},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'Người Dùng', 'verbose_name_plural': 'Danh sách người dùng'},
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='ton_toi_thieu',
            field=models.IntegerField(default=5, verbose_name='Tồn tối thiểu (Cảnh báo)'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên (Admin)'), ('THUKHO', 'Thủ kho'), ('KETOANKHO', 'Kế toán kho')], default='THUKHO', max_length=50, verbose_name='Vai trò'),
        ),
        migrations.CreateModel(
            name='PhieuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu')),
                ('loai_phieu', models.CharField(choices=[('NHAP', 'Phiếu Nhập Kho'), ('XUAT', 'Phiếu Xuất Kho')], max_length=10, verbose_name='Loại phiếu')),
                ('ngay_lap', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('nguoi_lap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.nguoidung', verbose_name='Người lập phiếu')),
            ],
            options={
                'verbose_name': 'Phiếu Kho',
                'verbose_name_plural': 'Quản lý Phiếu Kho',
                'db_table': 'PhieuKho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(verbose_name='Số lượng giao dịch')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Đơn giá tại thời điểm lập')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.hanghoa', verbose_name='Hàng hóa')),
                ('phieu_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='warehouse.phieukho', verbose_name='Phiếu kho')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu kho',
                'verbose_name_plural': 'Chi tiết các phiếu kho',
                'db_table': 'ChiTietPhieuKho',
            },
        ),
    ]
