# Generated by Django 6.1.1 on 2026-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_hanghoa_options_alter_nguoidung_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieukho',
            name='nha_cung_cap',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='gia_nhap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá nhập'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='gia_xuat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá xuất'),
        ),
    ]
