# Generated by Django 6.1.1 on 2026-09-04 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_phieukho_nha_cung_cap_alter_hanghoa_gia_nhap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=255, unique=True, verbose_name='Tên nhóm hàng')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Nhóm hàng',
                'verbose_name_plural': 'Các nhóm hàng',
                'db_table': 'NhomHang',
            },
        ),
        migrations.AlterModelOptions(
            name='hanghoa',
            options={'verbose_name': 'Hàng hóa', 'verbose_name_plural': 'Danh mục hàng hóa'},
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='gia_nhap',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá nhập'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='gia_xuat',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá xuất'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='ten_hang',
            field=models.CharField(max_length=255, verbose_name='Tên hàng'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='ton_toi_thieu',
            field=models.IntegerField(default=5, verbose_name='Tồn tối thiểu'),
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='nhom_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.nhomhang', verbose_name='Nhóm hàng'),
        ),
    ]
