# Generated by Django 6.1.1 on 2026-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_nhomhang_alter_hanghoa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ncc', models.CharField(max_length=50, unique=True, verbose_name='Mã nhà cung cấp')),
                ('ten_ncc', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
