# Generated by Django 6.1.1 on 2026-09-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_nhacungcap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhacungcap',
            options={'verbose_name': 'Nhà Cung Cấp', 'verbose_name_plural': 'Danh sách nhà cung cấp'},
        ),
        migrations.AddField(
            model_name='chitietphieukho',
            name='han_su_dung',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng'),
        ),
        migrations.AddField(
            model_name='chitietphieukho',
            name='ngay_san_xuat',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sản xuất'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterModelTable(
            name='nhacungcap',
            table='NhaCungCap',
        ),
    ]
