# Generated by Django 6.1.1 on 2026-09-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_nhacungcap_options_chitietphieukho_han_su_dung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cau_hinh', models.CharField(max_length=100, unique=True, verbose_name='Tên cấu hình')),
                ('gia_tri', models.CharField(max_length=255, verbose_name='Giá trị')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Cấu Hình Hệ Thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'db_table': 'CauHinhHeThong',
            },
        ),
        migrations.CreateModel(
            name='NhatKyHoatDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(max_length=255, verbose_name='Hành động')),
                ('chi_tiet', models.TextField(blank=True, null=True, verbose_name='Chi tiết')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.nguoidung', verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật Ký Hoạt Động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'db_table': 'NhatKyHoatDong',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
