# Generated by Django 6.1.1 on 2026-09-17 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_cauhinhhethong_nhatkyhoatdong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dvt', models.CharField(max_length=100, unique=True, verbose_name='Tên đơn vị tính')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Các đơn vị tính',
                'db_table': 'DonViTinh',
            },
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='don_vi_tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.donvitinh', verbose_name='Đơn vị tính'),
        ),
    ]
