# Generated by Django 6.1.1 on 2026-09-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_donvitinh_hanghoa_don_vi_tinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieukho',
            name='nha_cung_cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.nhacungcap', verbose_name='Nhà cung cấp'),
        ),
    ]
