# Generated by Django 6.1.1 on 2026-09-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_phieukho_nha_cung_cap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phieukho',
            options={'ordering': ['-ngay_lap'], 'verbose_name': 'Phiếu Kho', 'verbose_name_plural': 'Quản lý Phiếu Kho'},
        ),
        migrations.AlterField(
            model_name='phieukho',
            name='nguoi_lap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_kho_da_lap', to='warehouse.nguoidung', verbose_name='Người lập phiếu'),
        ),
        migrations.AlterField(
            model_name='phieukho',
            name='nha_cung_cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_kho', to='warehouse.nhacungcap', verbose_name='Nhà cung cấp'),
        ),
    ]
